version: '3.8'

services:
  nightscout:
    build: .
    container_name: nightscout
    restart: unless-stopped
    depends_on:
      - mongo
    ports:
      - "1337:1337"
    environment:
      ### Variables for the container
      NODE_ENV: production
      TZ: America/New_York  # Change to your timezone

      ### MongoDB connection (use environment variable for auth)
      MONGODB_URI: mongodb://root:${MONGO_INITDB_ROOT_PASSWORD:-change_this_password}@mongo:27017/nightscout?authSource=admin
      MONGO_COLLECTION: entries

      ### Required variables
      API_SECRET: change_this_to_a_long_random_string  # CHANGE THIS!
      
      ### Features
      ENABLE: careportal basal dbsize rawbg iob maker cob bwp cage iage sage boluscalc pushover treatmentnotify loop pump profile food openaps bage alexa override cors

      ### Core settings
      DISPLAY_UNITS: mg/dl  # or mmol/L
      DEFAULT_FEATURES: careportal boluscalc food rawbg iob
      ALARM_HIGH: 260
      ALARM_LOW: 55
      ALARM_URGENT_HIGH: 370
      ALARM_URGENT_LOW: 40

      ### Theme
      THEME: colors

      ### Language
      LANGUAGE: en

      ### Authentication
      AUTH_DEFAULT_ROLES: readable
      
      ### Optional: Custom title
      CUSTOM_TITLE: My Nightscout

    networks:
      - nightscout_network

  mongo:
    image: mongo:4.4
    container_name: nightscout_mongo
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-change_this_password}  # CHANGE THIS!
    networks:
      - nightscout_network

volumes:
  mongo_data:

networks:
  nightscout_network:
    driver: bridge